version: "3"

services:
    db:
        image: mysql:8.0
        container_name: db
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wp
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        networks:
            - wp

    wordpress:
        ports:
            - "8000:80"
        depends_on:
            - db
        image: wordpress:latest
        volumes: ["./html:/var/www/html"]
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
        networks:
            - wp
    networks:
        wp:
    volumes:
        db_data:
